### ISSUE TITLE
typo in hrtool

### ISSUE THREAD

**Issue by mjsduncan** [hansonrobotics/hansoncog#3] opened 2016-05-03 04:28 UTC
hi, in line 182 of hrtool:

`catkin clean -a`

i had to switch to 

`catkin -a clean` to avoid `catkin: error: unrecognized arguments: -a`

**Comment by wenwei-dev** [comment] 2016-05-03 05:51
This is caused by the incompatible upgrade of catkin_tools package. 

Change it to `catkin clean -y || catkin clean -a` should be fine.

**Comment by wenwei-dev** [comment] 2016-05-03 07:17
Fixed by PR #4

**Closed by wenwei-dev** 2016-05-03 07:17 UTC

**Comment by mjsduncan** [comment] 2016-05-03 13:30
thanks

<div>-------- Original message --------</div><div>From: Wenwei <notifications@github.com> </div><div>Date:05/03/2016  01:51  (GMT-05:00) </div><div>To: hansonrobotics/hansoncog <hansoncog@noreply.github.com> </div><div>Cc: mjsduncan <mjsduncan@gmail.com>,Author <author@noreply.github.com> </div><div>Subject: Re: [hansonrobotics/hansoncog] typo in hrtool (#3) </div><div>
</div>This is caused by the incompatible upgrade of catkin_tools package.

Change it to catkin clean -y || catkin clean -a should be fine.
